services:
  - type: web
    name: peep
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NITRO_PRESET
        value: render-com
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        sync: false
