/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as WorldWorldIdRouteImport } from './routes/world.$worldId'
import { Route as ApiWorldLoadRouteImport } from './routes/api/world/load'
import { Route as ApiWorldSaveRouteImport } from './routes/api/world/save'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldWorldIdRoute = WorldWorldIdRouteImport.update({
  id: '/world/$worldId',
  path: '/world/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldLoadRoute = ApiWorldLoadRouteImport.update({
  id: '/api/world/load',
  path: '/api/world/load',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldSaveRoute = ApiWorldSaveRouteImport.update({
  id: '/api/world/save',
  path: '/api/world/save',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/healthz': typeof HealthzRoute
  '/api/rtc': typeof ApiRtcRoute
  '/world/$worldId': typeof WorldWorldIdRoute
  '/api/world/load': typeof ApiWorldLoadRoute
  '/api/world/save': typeof ApiWorldSaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/healthz': typeof HealthzRoute
  '/api/rtc': typeof ApiRtcRoute
  '/world/$worldId': typeof WorldWorldIdRoute
  '/api/world/load': typeof ApiWorldLoadRoute
  '/api/world/save': typeof ApiWorldSaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/healthz': typeof HealthzRoute
  '/api/rtc': typeof ApiRtcRoute
  '/world/$worldId': typeof WorldWorldIdRoute
  '/api/world/load': typeof ApiWorldLoadRoute
  '/api/world/save': typeof ApiWorldSaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/healthz'
    | '/api/rtc'
    | '/world/$worldId'
    | '/api/world/load'
    | '/api/world/save'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/healthz'
    | '/api/rtc'
    | '/world/$worldId'
    | '/api/world/load'
    | '/api/world/save'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/healthz'
    | '/api/rtc'
    | '/world/$worldId'
    | '/api/world/load'
    | '/api/world/save'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  HealthzRoute: typeof HealthzRoute
  ApiRtcRoute: typeof ApiRtcRoute
  WorldWorldIdRoute: typeof WorldWorldIdRoute
  ApiWorldLoadRoute: typeof ApiWorldLoadRoute
  ApiWorldSaveRoute: typeof ApiWorldSaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$worldId': {
      id: '/world/$worldId'
      path: '/world/$worldId'
      fullPath: '/world/$worldId'
      preLoaderRoute: typeof WorldWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world/load': {
      id: '/api/world/load'
      path: '/api/world/load'
      fullPath: '/api/world/load'
      preLoaderRoute: typeof ApiWorldLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world/save': {
      id: '/api/world/save'
      path: '/api/world/save'
      fullPath: '/api/world/save'
      preLoaderRoute: typeof ApiWorldSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  HealthzRoute: HealthzRoute,
  ApiRtcRoute: ApiRtcRoute,
  WorldWorldIdRoute: WorldWorldIdRoute,
  ApiWorldLoadRoute: ApiWorldLoadRoute,
  ApiWorldSaveRoute: ApiWorldSaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
